from flask import Flask, render_template, request, session, send_file
from predictor import predict_url, predict_email

from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

from datetime import datetime
import io

app = Flask(__name__)
app.secret_key = "your_secret_key_here"


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/predict_url", methods=["POST"])
def predict_url_route():
    url = request.form.get("url", "").strip()

    if not url:
        return render_template(
            "index.html",
            url_result={
                "prediction": "Error",
                "confidence": 0,
                "message": "Please enter a URL."
            }
        )

    try:
        result = predict_url(url)

        # Save report data
        session["input_type"] = "URL"
        session["input_text"] = url
        session["prediction"] = result.get("prediction", "")
        session["confidence"] = result.get("confidence", 0)
        session["message"] = result.get("message", "")

    except Exception as e:
        result = {
            "prediction": "Error",
            "confidence": 0,
            "message": str(e)
        }

    return render_template(
        "index.html",
        url_result=result
    )


@app.route("/predict_email", methods=["POST"])
def predict_email_route():

    email_text = request.form.get("email", "").strip()

    if not email_text:
        return render_template(
            "index.html",
            email_result={
                "prediction": "Error",
                "confidence": 0,
                "message": "Please enter an email message."
            }
        )

    try:
        result = predict_email(email_text)

        # Save report data
        session["input_type"] = "Email"
        session["input_text"] = email_text
        session["prediction"] = result.get("prediction", "")
        session["confidence"] = result.get("confidence", 0)
        session["message"] = result.get("message", "")

    except Exception as e:
        result = {
            "prediction": "Error",
            "confidence": 0,
            "message": str(e)
        }

    return render_template(
        "index.html",
        email_result=result
    )


@app.route("/download_report")
def download_report():

    if "prediction" not in session:
        return "No prediction available. Please make a prediction first."

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>PHISHING DETECTION REPORT</b>", styles["Title"]))
    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            styles["Normal"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            f"<b>Input Type:</b> {session.get('input_type')}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Input:</b> {session.get('input_text')}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Prediction:</b> {session.get('prediction')}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Confidence:</b> {session.get('confidence')}%",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Message:</b> {session.get('message')}",
            styles["Normal"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            "<b>Generated by:</b><br/>"
            "Intelligent Multi-Layered Phishing Detection Framework",
            styles["Normal"]
        )
    )

    doc.build(story)

    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="Phishing_Report.pdf",
        mimetype="application/pdf"
    )


if __name__ == "__main__":
    app.run(debug=True)